### ISSUE TITLE
添加可配置忽略本地哪些文件不添加 data-type=mip

### ISSUE THREAD

**Issue by xuexb** [xuexb/hexo-generator-mip#2]
如：

``` yaml
mip:
  excludeHref:
    - /xx.html
    - /about.html
```
